version: '3'
services:
    zookeeper:
        container_name: zookeeper
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        environment:
          - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        container_name: kafka
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
          - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
          - zookeeper


    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes: 
            - mongodb_data_container:/data/db


    charts:
      build:
        context: 'docker/charts'
        args:
          - EMAIL=admin@mail.com
          - PASSWORD=secret
      image: 84c23ddf6527
      ports:
        - 8080:80
      environment:
        CHARTS_SUPPORT_WIDGET_AND_METRICS: 'on'
        CHARTS_MONGODB_URI: 'mongodb://root:secret@mongodb:27017'
      volumes:
        - keys:/mongodb-charts/volumes/keys
        - logs:/mongodb-charts/volumes/logs
        - db-certs:/mongodb-charts/volumes/db-certs
        - web-certs:/mongodb-charts/volumes/web-certs
      depends_on:
        - mongodb
      container_name: charts

    # dask-scheduler:
    #   build:
    #     context: ./docker/dask
    #     dockerfile: Dockerfile
    #   image: daskdev/dask
    #   hostname: dask-scheduler
    #   ports:
    #     - "8786:8786"
    #     - "8787:8787"
    #   command: ["dask-scheduler"]
    #   container_name: dask-scheduler
  
    # dask-worker:
    #   build:
    #     context: ./docker/dask
    #     dockerfile: Dockerfile
    #   image: daskdev/dask
    #   hostname: dask-worker
    #   command: ["dask-worker", "tcp://dask-scheduler:8786"]
    #   container_name: dask-worker

volumes: 
    mongodb_data_container:
    keys:
    logs:
    db-certs:
    web-certs: